// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnhimfnwkwhusiggcowq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduaGltZm53a3dodXNpZ2djb3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTEwNTMsImV4cCI6MjA2ODg2NzA1M30.N474xWNoT-EjLrVV02fXrjIKDUxMRpoOmgWdCq_ylRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});